CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(50)                             NOT NULL,
    username VARCHAR(20)                             NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     user_role                               NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_username UNIQUE (username)
);