CREATE TABLE customers
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(50)                             NOT NULL,
    phone    VARCHAR(11)                             NOT NULL,
    street   VARCHAR(255)                            NOT NULL,
    city     VARCHAR(255)                            NOT NULL,
    state    VARCHAR(255)                            NOT NULL
);