CREATE TABLE customers
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(50)                             NOT NULL,
    phone  VARCHAR(11),
    street VARCHAR(255),
    city   VARCHAR(255),
    state  VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);