CREATE TYPE product_status AS ENUM
    (
        'ACTIVE',
        'INACTIVE'
        );

CREATE TABLE products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(100)                            NOT NULL,
    description     VARCHAR(255),
    retail_price    DECIMAL(10, 2)                          NOT NULL,
    wholesale_price DECIMAL(10, 2)                          NOT NULL,
    status          product_status                          NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT pk_products PRIMARY KEY (id)
);

